apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: argo
  namespace: flux-system
spec:
  url: https://argoproj.github.io/argo-helm
  interval: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo
  namespace: flux-system
spec:
  interval: 3m
  chart:
    spec:
      chart: argo-cd
      version: "3.2.2"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
      interval: 1m
